advisor_major_ug = {
    'BACT-Accounting': 'Nina',
    'BADM-Business Administration': 'Nina',
    'BENI-Entrepreneurship & Innovation': 'Nina',
    'BMGT-Management': 'Nina',
    'BNTL-International Business': 'Nina',
    'BMKT-Marketing': 'Nina',
    'BFIN-Finance': 'Nina',
    'HM-Hospitality Management': 'Nina',
    'UNBN-Undeclared Business': 'Nina',
    'CS-Computer Science': 'Nathan',
    'COMS-Communication Studies': 'Nathan',
    'CHEM-Chemistry': 'Nathan',
    'POLS-Politics': 'Nathan',
    'HIST-History': 'Nathan',
    'BIO-Biology': 'Nathan',
    'BAIS-International Studies': 'Nathan',
    'UNLA-Undeclared Arts': 'Nathan',
    'UNSC-Undeclared Sciences': 'Nathan',
    'ADVT-Advertising': 'Nathan',
    'LAW-Law': 'Nathan',
    'PSYC-Psychology': 'Nathan',
    'ECON-Economics': 'Nathan',
    'ARCD-Architecture & Community Desig': 'Nathan',
    'BSDS-Data Science':'Nathan',
    'ENVS-Environmental Science':'Nathan',
    'ENVA-Environmental Studies': 'Nathan',
    'ENGL-English': 'Nathan',
    'CMPL-Comparative Lit. & Culture': 'Nathan',
    'ICL-Intl Transaction & Comp. Law':'Nathan',
    'IPTL-Intellectual Property Tech Law': 'Nathan',
    'MATH-Mathematics': 'Nathan',
    'MS-Media Studies': 'Nathan',
    'FNAR-Fine Arts': 'Nathan',
    'PASJ-Perf. Arts & Soc. Justice': 'Nathan',
    'PHIL-Philosophy': 'Nathan',
    'PHYS-Physics': 'Nathan',
    'SOC-Sociology': 'Nathan',
    'DSGN-Design': 'Nathan',
    'KIN-Kinesiology': 'Nathan',
    'JNST-Japanese Studies': 'Nathan',
    'ANST-Asian Studies': 'Nathan',
    'BIOL-Biology':'Nathan',
    'URBS-Urban Studies': 'Nathan',
    'WRIT-Writing': 'Nathan'
     }

advisor_major_gr = {
    'IDEC-Intl & Development Economics': 'Marcella',
    'ARTM-Art History/Arts Management': 'Marcella',
    'CSBR-Computer Science Bridge': 'Marcella',
    'ENVS-Environmental Science': 'Marcella',
    'ECON-Economics': 'Marcella',
    'CHEM-Chemistry': 'Marcella',
    'ENGY-Energy Systems Management': 'Marcella',
    'MSEM-Environmental Management': 'Marcella',
    'MAIS-International Studies': 'Marcella',
    'MAPC-Professional Communication': 'Marcella',
    'CPSY-Counseling Psychology': 'Marcella',
    'CAPS-Asia Pacific Graduate Studies': 'Marcella',
    'APS-Asia Pacific Studies': 'Marcella',
    'BTEC-Biotechnology': 'Marcella',
    'CSBR-Computer Science': 'Marcella',
    'PA-Public Affairs': 'Marcella',
    'PSYD-Psychology': 'Marcella',
    'SM-Sport Management': 'Macella',
    'SM-Sports Management': 'Marcella',
    'UPA-Urban and Public Affairs':'Marcella',
    'CEL-Catholic Educational Leadership': 'Cynthia',
    'THES-Theology & Religious Studies': 'Marcella',
    'CSF-Computer Science (4+1)': 'Marcella',
    'MS-Data Science': 'Cynthia',
    'IME-Intl and Multicultural Educ.': 'Cynthia',
    'NURS-Nursing': 'Cynthia',
    'MBA-Business Administration': 'Cynthia',
    'MNAF-Nonprofit Administration': 'Cynthia',
    'MSHI-Health Informatics': 'Cynthia',
    'MSBH-Behavorial Health': 'Cynthia',
    'MSEI-Entrepreneurship Innovation': 'Cynthia',
    'MSFA-Financial Analysis': 'Cynthia',
    'MSFN-Financial Analysis': 'Cynthia',
    'MSAN-Analytics': 'Cynthia',
    'EDUC-Education': 'Cynthia',
    'L&I-Learning and Instruction': 'Cynthia',
    'MPH-Public Health': 'Cynthia',
    'O&L-Organization and Leadership':'Cynthia',
    'TSOL-Teach Engl/Speakers Other Lang': 'Cynthia'
}

master_deg_adv = {
    'Master of Arts':'Marcella',
    "'Professional Science Master's":'Marcella',
    'Master of Science':'Marcella',
    'Master of Public Health':'Cynthia',
    'Doctor of Education':'Cynthia',
    'Master of Science in Nursing':'Cynthia',
    'Master of Public Affairs':'Cynthia',
    'Master in Global Entrprnr/Mgt':'Cynthia',
    'Master of Business Admin': 'Cynthia'
}


bachelor_deg_adv = {
    'BS in Business Administration': 'Nina',
    'Bachelor of Arts': 'Nathan',
    'Bachelor of Science': 'Nathan',
    'Master of Laws': 'Nathan',
    'Juris Doctor': 'Nathan',
    'Bachelor of Science in Nursing': 'Nathan'
}
